title: Igow Brindes
description: >- # this means to ignore newlines until "baseurl:"
  A IGOW BRINDES está localizada em Apucarana, no Norte do Paraná, e
  vem se destacando cada vez mais no mercado de brindes promocionais.
baseurl: "/igowbrindes"
url: "https://conttudoweb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: #00a859

# Build settings
markdown: kramdown
parmalink: /:title/
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
